spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://43.200.32.212:9411/
    enabled: true
  sleuth:
    sampler:
      # 얼마나 많은 비율로 zipkin에 transaction을 전송할 것인가
      probability: 1.0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://localhost:3306/task_agile?characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: scott
    password: '{cipher}2515ace4b4a757c7e6cd0c4076d3de44f202e310b2116500a55e62c5b47ef07a'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      # 기본키 생성전략
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        #        show_sql: ture
        format_sql: true
        # 여러개 쿼리 나가야할 것을 in으로 한번에 가져옴
        default_batch_fetch_size: 100
        jdbc.batch_size: 50
        # bulk
        order_inserts: true
        order_updates: true
        dialect:
          storage_engine: innodb
    open-in-view: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

cloud:
  aws:
    credentials:
      access-key: abc
      secret-key: eeee
    s3:
      bucket: camping-kr
    region:
      static: ap-northeast-2
    stack:
      auto: false

my:
  server:
    ip: http://43.200.32.212

jwt:
  header: Authorization
  secret: '{cipher}2cfaf74f35c6ceab1fe28c6227a5aceb3a9c1a8ad9c4d4481361f1366e27e2e1e8f0a0652718349b8d5e08a0d916f47df784fa02d0efae385d880e4307b796490dc0cbec79df468fde748be0761990fb5b76dc22c3ce98d58a1fd8e032600bfb'
  # 30분
  access-token-expire-time: 18000
  #  access-token-expire-time: 10
  # 1일
  refresh-token-expire-time: 86400
#  refresh-token-expire-time: 10

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace


# 로그파일 저장 위치
logserver:
  path: C:\log