spring:
  rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://localhost:3306/task_agile?characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: scott
    password: '{cipher}8117f1f64f7047e10ebf763f8a42501ee7bf7f1c03b7703c83bf0dbaefb6e6e1'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
      # 기본키 생성전략
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        #        show_sql: ture
        format_sql: true
        # 여러개 쿼리 나가야할 것을 in으로 한번에 가져옴
        default_batch_fetch_size: 100
        jdbc.batch_size: 50
        # bulk
        order_inserts: true
        order_updates: true
        dialect:
          storage_engine: innodb
    open-in-view: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

cloud:
  aws:
    credentials:
      access-key: abc
      secret-key: eeee
    s3:
      bucket: camping-kr
    region:
      static: ap-northeast-2
    stack:
      auto: false

my:
  server:
    ip: http://43.200.32.212

jwt:
  header: Authorization
  secret: '{cipher}c3d5462930a3d3987748d905e703e3dbc533f5262646890f4153f32a6d3749dc55c9481bc0e3d8590b47638655097228fa6340bb017a2123df5360a9126396bf'
  # 30분
  access-token-expire-time: 18000
  #  access-token-expire-time: 10
  # 1일
  refresh-token-expire-time: 86400
#  refresh-token-expire-time: 10

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace


# 로그파일 저장 위치
logserver:
  path: C:\log