spring:
  rabbitmq:
    host: b-30d5fceb-8119-4270-ba48-b7cd3d155416.mq.ap-northeast-2.amazonaws.com
    port: 5671
    username: camping
    password: '{cipher}a8a92f0012fc9d3e665148fd54f891d7f479baf3a8488d3606c7338c7df1cc5afca5cf259a5a7a56e6218143b812d8e8'
    ssl:
      enabled: true
    listener:
      simple:
        acknowledge-mode: manual
  zipkin:
    base-url: http://43.200.32.212:9411/
    enabled: true
  sleuth:
    sampler:
      # 얼마나 많은 비율로 zipkin에 transaction을 전송할 것인가
      probability: 1.0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://camping-db.c6yfcwwadzxw.ap-northeast-2.rds.amazonaws.com:3306/camping?characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: scott
    password: '{cipher}65289ca9d55a78bf34369ace3a7df091af667389e3d09d9426370f41c04f96da'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      # 기본키 생성전략
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        #        show_sql: ture
        format_sql: true
        # 여러개 쿼리 나가야할 것을 in으로 한번에 가져옴
        default_batch_fetch_size: 100
        jdbc.batch_size: 50
        # bulk
        order_inserts: true
        order_updates: true
        dialect:
          storage_engine: innodb
    open-in-view: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

cloud:
  aws:
    credentials:
      access-key: '{cipher}86ba90efac75b11dc3cab958c009c385fe7d9adcb61ac733ce7a96e63c8e10af14cbb8b282808e99f4438e8141d7f489'
      secret-key: '{cipher}3e33bed3fdcffaae36f5376077076aa508d50b2486f124a171eeba44987deafece4a29a4d3d468b7a26ea3e676e36d46c6e3690db26ee56edcd682954f8a687c'
    s3:
      bucket: camping-kr
    region:
      static: ap-northeast-2
    stack:
      auto: false

my:
  server:
    ip: http://43.200.32.212

jwt:
  header: Authorization
  secret: '{cipher}bd53a8f9bee3611865aecc3b04e154b1547fda4354f570c82943379860aea276b8e868d3355f155a98175fbc1bfd4609212135934f7b9116a9232e928daa41f5fdab956f2c56c21c2b7584a170e44008f24995537f49e239931e6d0eadb41eefd1ff4398e336c434a462945680b03f2caf2563cdcca69ee9b32258b10cca77ac'
  # 30분
  access-token-expire-time: 18000
  #  access-token-expire-time: 10
  # 1일
  refresh-token-expire-time: 86400
#  refresh-token-expire-time: 10

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace


# 로그파일 저장 위치
logserver:
  path: C:\log


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:9761/eureka