server:
  port: 9888


spring:
  application:
    name: config-service
  rabbitmq:
    host: b-30d5fceb-8119-4270-ba48-b7cd3d155416.mq.ap-northeast-2.amazonaws.com
    port: 5671
    username: camping
    password: ${ rabbitmq.password }
#    virtual-host: /camping
    ssl:
      enabled: true
    listener:
      simple:
        acknowledge-mode: manual
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Camping-Side/camping-config-serivce.git
          default-label: master
#          private repository ??...
#          username: [your username]
#          password: [your password]
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

# 로그파일 저장 위치
logserver:
  path: /tmp

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace