server:
  port: 9888


spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Camping-Side/camping-config-file.git
          default-label: main
#          private repository ??...
#          username: [your username]
#          password: [your password]

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
