version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/github_action
    overwrite: yes

permissions:
  - object: /home/ubuntu/github_action
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - file

hooks:
  ApplicationStart:
    - location: ./gh_deploy.sh
      timeout: 60
      runas: ubuntu